export { Hero } from "./hero"
export { About } from "./about"
export { Skills } from "./skills"
export { Experience } from "./experience"
export { Projects } from "./projects"
export { Achievements } from "./achievements"
export { Contact } from "./contact"
